nhsalpha/connecting-to-services-hack-day

- app/lib/pharmaciesParser.js
> :straight_ruler: Convert KMs to Miles

- app/middleware/gp.js
The most remote postcode I can find belongs to Hugh Town in the Isles of Scilly
and there are 10 pharmacies within 33 Kms e.g.
http://www.nhs.uk/service-search/Pharmacy/tr21/Results/13/-5.93227338790894/50.015251159668/10/0?distance=25
> :triangular_ruler: Reduce range to 35 Km

- app/views/includes/beta-header.nunjucks
- app/views/stomach-ache.nunjucks
- public/css/beta-style.css
> :bug: Sort out content styling

- app/views/results.nunjucks
- app/views/search.nunjucks
> :rewind: Add back button to search and results

- app/views/results.nunjucks
> :ticket: Pass postcode to GP search

- app/views/results.nunjucks
> :japan: Make it clear the button is not directions

- app/views/stomach-ache.nunjucks
> :flashlight: Make stomach ache CTA clearer

- app/views/search.nunjucks
> :barber: Add style to search page

- app/lib/WICParser.js
- app/lib/pharmacyMapper.js
- app/lib/wicMapper.js
- app/middleware/services.js
- config/routes.js
Fixes #39 (address, still needs formatting re: #32)
Fixes #40 (telephone number, need to have something for when there is no number available)
Fixes #41 (makes the map button work)
> :mag_right: Add address, telephone and coords for WIC

- app/views/includes/beta-header.nunjucks
- app/views/includes/header.nunjucks
> :dart: Update warning banner

- app/views/results.nunjucks
Fixes #69
Fixes #71
Fixes #71
Fixes #32
> Results page tweaks

- app/views/error.nunjucks
- app/views/index.nunjucks
- app/views/layout.nunjucks
- app/views/rashes.nunjucks
- app/views/results.nunjucks
- app/views/search.nunjucks
- app/views/stomach-ache.nunjucks
Using the awesome vim command
`:args app/views/*.nunjucks | argdo execute "normal gg=G" | update`
> :beer: Indent *.nunjucks files

- app/lib/wicMapper.js
> :wavy_dash: Add WIC opening times (hard coded)

- app/views/results.nunjucks
- public/css/style.css
- public/images/icon-button-start.svg
> :art: Make results page more like design

- app/lib/dateUtils.js
- app/lib/pharmacyMapper.js
- app/middleware/services.js
- app/views/index.nunjucks
- app/views/results.nunjucks
- test/unit/dateUtils.js
Also, resolved problem with mutating moments breaking the override setting
of now().
> Add informative next open/closed messages

- app/views/results.nunjucks
> :phone: Do not display word when no data available

- .istanbul.yml
- app/lib/dateUtils.js
- app/lib/pharmacyMapper.js
- app/lib/wicMapper.js
- app/middleware/services.js
- app/views/results.nunjucks
Also, add opening times message for WIC's
Fixes #90
> :clock1: Display WIC opening times as am/pm

- public/css/beta-style.css
- public/css/style.css
> :point_left: Left align banner text

- app/views/results.nunjucks
> :mask: Hide link for more info when there is none

- app/views/index.nunjucks
> :new: Make function of button clear

- app/views/search.nunjucks
> :ok_hand: Add useful instruction

- app/views/search.nunjucks
> :fast_forward: Clarify function of button

- app/views/results.nunjucks
> :symbols: Fix typo

- app/views/index.nunjucks
> :joy_cat: Add Saturday 07:30

- app/lib/WICParser.js
- app/lib/pharmaciesParser.js
> :arrow_down_small: Shorten results list.

- app/views/head-ache.nunjucks
- app/views/rashes.nunjucks
- app/views/results.nunjucks
- app/views/search.nunjucks
- app/views/stomach-ache.nunjucks
Fixes #111
Fixes #112 
Fixes #113
> Content & link changes
